### ISSUE TITLE
Thread 3: EXC_BAD_ACCESS (code=2, address=0x190d3eec)

### ISSUE THREAD

**Issue by nrsantos** [kitolog/sockets-for-cordova#1]
Hi,

I'm getting an error on SocketAdapter.m, line 207 with description Thread 3: EXC_BAD_ACCESS (code=2, address=0x190d3eec).

I saw that you fixe some errors, do you know anything about this one?

In iOS 11 it's ok but not on iOS 10.

Thanks

**Comment by kitolog** [comment]
Did you reproduce it again?

**Comment by kitolog** [comment]
No feedback

**Comment by attex** [comment]
I got the same issue. 

Every time i send a image i get EXC_BAD_ACCESS 

It does not occur on a small png with 2 Kb, but does indeed occur on a jpg with 1 Mb.

**Comment by attex** [comment]
So i figured that videos work as well until the size becomes more than circa 522.000 Bytes.
