### ISSUE TITLE
errorMessage

### ISSUE THREAD

**Issue by torosushi** [kitolog/sockets-for-cordova#12]
Hi, I tried socket.open('http://192.168.1.31',9100, function(...
and get {"errorMessage":"http://192.168.1.31","socketKey":"key","code":0}

How do I solve this error? Thank you.

**Comment by kitolog** [comment]
Hi
May you provide more information about OS and some debug data from Xcode or Android Studio?

**Comment by kitolog** [comment]
No details provided
