### ISSUE TITLE
Socket unusable if connection failed

### ISSUE THREAD

**Issue by heinerlamprecht** [kitolog/sockets-for-cordova#3]
Hi,

we are facing a severe issue on iOS:  If opening a socket has failed, eg. because the provided host/ip or port is wrong, or because the server does not respond or is not reachable, it is not possible to open a new connection anymore.  Even restarting the app or the device does not help.

Only solution so far:  Uninstall the app and install it again.

XCode shows the following error messages:

`To Native Cordova ->  SocketsForCordova open SocketsForCordova1368615857 ["options": [068d0855-72d0-668a-b7ed-831cc656c724, 192.168.200.128, 30809]]`
`2020-01-07 14:47:54.483263+0100 App[44431:10335628] [NATIVE] OPEN socket for port: 30809`
`2020-01-07 14:47:54.483534+0100 App[44431:10339415] -[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0xcb4ccf2d6dfc1595`

Any help is highly appreciated.

Thanks,  Heiner

**Comment by heinerlamprecht** [comment]
After further debugging, I found the root cause of the issue.  Although the parameter "port" is stored in a variable of type "NSNumber", it may not always be a number.  JavaScript is not type-save, so if the socket.open call in Js provides the port as a string, it is also stored as a string inside the plugin.  Calling "open" on the socketAdapter however leads to the error message (see above).

**Comment by kitolog** [comment]
merged pull request with ports check
